export enum SCREENS {
  HOME = 'HOME',
  PRODUCT_DETAIL = 'PRODUCT_DETAIL',
  BASKET = 'BASKET',
  FAVORITES = 'FAVORITES',
  SIGN_UP = 'SIGN_UP',
  SIGN_IN = 'SIGN_IN',
  AUTH_INIT = 'AUTH_INIT',
  HOME_TABS = 'HOME_TABS',
  PROFILE = 'PROFILE',
  EMAIL_VERIFICATION = 'EMAIL_VERIFICATION',
}
