export enum Colors {
  PRIMARY = '#E96E6E',
  ON_PRIMARY = '#FFFFFF',

  BACKGROUND_GRADIENT_START = '#FFD7DE',
  BACKGROUND_GRADIENT_END = '#FFFBFC',

  SURFACE = '#FFFFFF',

  TEXT_PRIMARY = '#000000',
  TEXT_SECONDARY = '#444444',
  TEXT_TERTIARY = '#797979',
  TEXT_INPUT = '#B6B6B6',

  ICON_PRIMARY = '#E96E6E',
  ICON_SECONDARY = '#C0C0C0',

  ERROR = '#E74C3C',
  SUCCESS = '#2ECC71',
  WARNING = '#F1C40F',
}
